# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cpplint:
    name: cpplint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cpplint
          path: ~/.cache/pip

      - name: Pyhton
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: cpplint
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cpplint
          cpplint \
            --repository=. \
            --recursive \
            --filter=-whitespace/line_length,-whitespace/braces,-whitespace/comments,-runtime/indentation_namespace,-whitespace/indent,-readability/braces,-whitespace/newline,-readability/todo,-build/c++11 \
            src

  platformio:
    name: pio ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: esp32dev|arduino-2
            board: esp32dev
            platform: espressif32@6.10.0
            opts:
          - name: esp32dev|arduino-3
            board: esp32dev
            platform: espressif32
            opts: "--project-option 'platform=https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip'"

          - name: esp32-s3-devkitc-1|arduino-2
            board: esp32-s3-devkitc-1
            platform: espressif32@6.10.0
            opts:
          - name: esp32-s3-devkitc-1|arduino-3
            board: esp32-s3-devkitc-1
            platform: espressif32
            opts: "--project-option 'platform=https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip'"

    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cache/pip
          key: ${{ matrix.name }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install platformio
      - run: platformio platform install ${{ matrix.platform }}

      - name: Build TaskMonitor
        run: platformio ci "examples/TaskMonitor/TaskMonitor.ino" -l '.' -b ${{ matrix.board }} ${{ matrix.opts }}

      - name: Build TaskMonitorJson
        run: PLATFORMIO_BUILD_FLAGS="-DMYCILA_JSON_SUPPORT" platformio ci "examples/TaskMonitorJson/TaskMonitorJson.ino" -l '.' --project-option="lib_deps=bblanchon/ArduinoJson" -b ${{ matrix.board }} ${{ matrix.opts }}
